#!/usr/bin/env python3
"""Hand-curated McKinsey TTO edition files (entries chosen from parse.py candidates), with a verbatim check of each quote.

Usage: python3 build.py <download dir>   (writes data/raw/mckinsey-tech-trends/<edition>.json)
"""
import json, re, sys
from pathlib import Path

HERE = Path(sys.argv[1] if len(sys.argv) > 1 else ".")  # folder with the downloads and pdftotext output
OUT = Path(__file__).resolve().parents[2] / "data" / "raw" / "mckinsey-tech-trends"
PUB = "McKinsey & Company (McKinsey Technology Council)"
SERIES = "McKinsey Technology Trends Outlook"
M = "https://www.mckinsey.com/~/media/mckinsey/business%20functions/mckinsey%20digital/our%20insights/"
URL = {
    "2021": M + "the%20top%20trends%20in%20tech%20final/tech-trends-exec-summary.pdf",
    "2022": M + "the%20top%20trends%20in%20tech%202022/mckinsey-tech-trends-outlook-2022-full-report.pdf",
    "2023": M + "the%20top%20trends%20in%20tech%202023/mckinsey-technology-trends-outlook-2023-v5.pdf",
    "2024": M + "the%20top%20trends%20in%20tech%202024/mckinsey-technology-trends-outlook-2024.pdf",
    "2025": M + "the%20top%20trends%20in%20tech%202025/mckinsey-technology-trends-outlook-2025.pdf",
    "2026": "https://www.mckinsey.com/capabilities/tech-and-ai/our-insights/the-top-trends-in-tech",
}
WAYBACK = {
    "2021": "https://web.archive.org/web/20210930082044/" + URL["2021"],
    "2022": "https://web.archive.org/web/20220910124235/" + URL["2022"],
    "2023": "https://web.archive.org/web/20250201232726/" + URL["2023"],
    "2024": "https://web.archive.org/web/20240717233936/" + URL["2024"],
    "2025": "https://web.archive.org/web/20250728164924/" + URL["2025"],
    "2026": "https://web.archive.org/web/20260915183134/" + URL["2026"],
}


def norm(s):
    s = s.replace("­", "")
    s = re.sub(r"[\s\-‐‑–—]+", "", s)
    return s.lower()


def T(rank, label, section, quote, subject, note=None, conf="high"):
    return dict(rank=rank, label=label, section=section, quote=quote, subject=subject,
                kind="trend", confidence=conf, note=note)


def F(rank, label, section, quote, subject, target_year, metric=None, value=None, unit=None,
       horizon=None, note=None, conf="high"):
    return dict(rank=rank, label=label, section=section, quote=quote, subject=subject,
                horizon=horizon, target_year=target_year, metric=metric, value=value, unit=unit,
                kind="forecast", confidence=conf, note=note)


def inv(y, i, j, iy, jy):
    return f"Report states (past-year context, not a forecast): equity investment {iy}: {i}; job postings {jy}: {j}."


E = {}

# ---------------------------------------------------------------- 2021
s1, s2 = "Industry-agnostic trends", "Industry-specific trends"
r = "Quote reconstructed from slide columns (pdftotext layout)."
E["2021"] = [
    T(1, "Next-level process automation and virtualization", s1,
      "Self-learning, reconfigurable robots will drive automation of physical processes beyond routine activities to include less predictable ones",
      "Process automation and virtualization", r + " Underlying technologies listed: Industrial IoT, robots/cobots/RPA, digital twins, 3-D/4-D printing."),
    F(1, "Next-level process automation and virtualization", s1, "50% of today’s work activities could be automated by 2025",
      "Automation of work activities", 2025, "share of today's work activities that could be automated", "50", "percent",
      note=r + " Slide 'Effects of technology trends up to 2050'."),
    T(2, "Future of connectivity", s1,
      "enhanced coverage and speed of connections across long and short distances will enable new services (eg, remote patient monitoring), business models (eg, connected services), and next-generation customer experiences (eg, live VR)",
      "5G and IoT connectivity", r),
    F(2, "Future of connectivity", s1, "Up to 80% of global population could be reached by 5G coverage by 2030",
      "5G population coverage", 2030, "share of global population reached by 5G coverage", "up to 80", "percent",
      note=r + " Footnote: either high-band or low- to mid-band 5G coverage. Restated on slide 8."),
    T(3, "Distributed infrastructure", s1,
      "Wide availability of IT infrastructure and services through cloud computing could shift demand for on-premise IT infrastructure and reduce the need for IT setup and maintenance",
      "Cloud and edge computing", r),
    F(3, "Distributed infrastructure", s1, ">75% of enterprise-generated data will be processed by edge or cloud computing by 2025",
      "Cloud and edge data processing", 2025, "share of enterprise-generated data processed by edge or cloud computing", ">75", "percent", note=r),
    T(4, "Next-generation computing", s1,
      "High computational capabilities allow new use cases, such as molecule-level simulation, reducing the empirical expertise and testing needed for a range of applications",
      "Quantum computing and ASICs", r),
    F(4, "Next-generation computing", s1, ">$1 trillion value potential of quantum-computing use cases at full scale by 2035",
      "Quantum computing value", 2035, "value potential of quantum-computing use cases at full scale", ">1", "USD trillion", note=r),
    T(5, "Applied AI", s1,
      "As AI matures and continues to scale, it will enable new applications (eg, more rapid development cycles and detailed customer insights)",
      "Applied AI", r + " Slide 7 also states '>75% of all digital-service touch points (eg, voice assistants) will see improved usability, enriched personalization, and increased conversion' with no year (slide title: effects up to 2050); not captured as a forecast."),
    T(6, "Future of programming", s1, "Software 2.0 creates new ways of writing software and reduces complexity",
      "Software 2.0", r + " Slide 7: '~30× reduction in the working time required for software development', no year; not captured as a forecast."),
    T(7, "Trust architecture", s1,
      "Trust architectures help commercial entities and individuals establish trust and conduct business without need for intermediaries, even as zero-trust-security measures address growing cyberattacks",
      "Zero-trust security and blockchain", r),
    F(7, "Trust architecture", s1, "~10% of global GDP could be associated with blockchain by 2027",
      "Blockchain", 2027, "share of global GDP associated with blockchain", "~10", "percent", note=r),
    T(8, "Bio Revolution", s2,
      "“-omics” enable rapid analysis of genetic materials and open up possibilities (eg, for rapid vaccine development, personalized medicine, and gene therapy)",
      "Biotechnology (omics, biomachines)", r + " Slide 7 past figure: 45× cost reduction for sequencing the human genome in the past 10 years."),
    T(9, "Next-generation materials", s2,
      "next-generation materials may change industry economics and reconfigure companies within them",
      "Advanced materials (nanomaterials, graphene, 2-D materials)", r + " Slide 7 past figure: 10× growth in number of patents between 2008 and 2018."),
    T(10, "Future of clean technologies", s2,
      "As clean technologies come down the cost curve, they become increasingly disruptive to traditional business models",
      "Clean energy technologies", r + " Underlying technologies: nuclear fusion, smart distribution/metering, battery storage, carbon-neutral energy generation."),
    F(10, "Future of clean technologies", s2, ">75% of global energy will be produced by renewables in 2050",
      "Renewable energy share", 2050, "share of global energy produced by renewables", ">75", "percent", note=r),
]

# ---------------------------------------------------------------- 2022
a, b = "Silicon Age", "Engineering Tomorrow"
s = "Figure label on the trend's 'Why should leaders pay attention?' slide; quote reconstructed from slide columns."
E["2022"] = [
    T(1, "Advanced connectivity", a,
      "5G/6G cellular, wireless low-power networks, low-Earth-orbit satellites, and other technologies support a host of digital solutions that can help networks increase geographic coverage, reduce latency, reduce energy consumption, increase data throughput, and increase spectrum efficiency",
      "Advanced connectivity (5G/6G, LPWA, LEO satellites)", "No per-trend equity investment or adoption figure in the PDF text (only in the bubble exhibit)."),
    F(1, "Advanced connectivity", a, "~51.9 billion Total number of connected devices expected in 2025, up from 43 billion in 2020",
      "Connected devices", 2025, "connected devices worldwide", "~51.9", "billion devices", note=s + " Sources listed on the slide include IDC forecasts."),
    T(2, "Applied AI", a,
      "Applied AI uses intelligent application to solve classification, prediction, and control problems to automate, add, or augment real-world business use cases.",
      "Applied AI"),
    T(3, "Cloud and edge computing", a, "Cloud has already effected change across industries and will remain an important tech disruption",
      "Cloud and edge computing"),
    F(3, "Cloud and edge computing", a, "$1 trillion Opportunity in run-rate EBITDA across Fortune 500 companies in 2030 through cloud cost optimization levers and value-oriented business use cases",
      "Cloud value", 2030, "run-rate EBITDA opportunity across Fortune 500 companies from cloud", "1", "USD trillion", note=s + " Source on slide: McKinsey, 'Cloud's trillion-dollar prize is up for grabs', Feb 2021."),
    F(3, "Cloud and edge computing", a, "~$250 billion Projected worldwide spending on edge computing in 2025, growing at a CAGR of ~10%",
      "Edge computing spending", 2025, "worldwide spending on edge computing", "~250", "USD billion", note=s + " Slide source line: IDC; Omdia."),
    F(3, "Cloud and edge computing", a, "26% Forecast share of servers shipped in 2024 that will be deployed at the edge—up from 20% in 2019",
      "Edge servers", 2024, "share of servers shipped that are deployed at the edge", "26", "percent", note=s + " Slide source line: IDC; Omdia."),
    T(4, "Immersive-reality technologies", a, "Immersive-reality technologies will have a significant role to play in the metaverse",
      "Immersive reality (AR/VR/MR)"),
    F(4, "Immersive-reality technologies", a, "Global immersive-reality market size is expected to grow at a CAGR of ~24% until 2035",
      "Immersive-reality market", 2035, "global immersive-reality market size", "~1.2", "USD trillion",
      note=s + " Slide headline figure: '~$1.2 trillion market size by 2035'. Sources include ABI Research and Emergen Research."),
    F(4, "Immersive-reality technologies", a, "~66% CAGR in enterprise adoption of AR through 2026",
      "Enterprise AR adoption", 2026, "CAGR of enterprise adoption of AR", "~66", "percent per year", note=s),
    T(5, "Industrializing machine learning", a,
      "Solutions industrializing ML provide the software and hardware technologies to scale ML workflows and ease the development and deployment of ML for organizations",
      "MLOps"),
    T(6, "Next-generation software development", a,
      "Developers will focus more on the capabilities their applications would enable than on the details of building the apps",
      "Software development tooling (low-code, AI-assisted)"),
    F(6, "Next-generation software development", a, "~70% Share of new application development that will leverage low-code/no-code by 2025 (vs <25% in 2020)",
      "Low-code/no-code development", 2025, "share of new application development using low-code/no-code", "~70", "percent", note=s + " Sources on slide include Gartner."),
    F(6, "Next-generation software development", a, "~21% Growth in size of market for software development, CAGR for 2021–26, reaching ~$600 million by 2026",
      "AI software development market", 2026, "market size for software development (AI)", "~600", "USD million",
      note=s + " Slide source: IndustryARC 'Software development AI market overview'; the label does not say 'AI', so the market scope is unclear.", conf="medium"),
    T(7, "Quantum technologies", a, "The quantum age is just over the horizon …", "Quantum technologies"),
    F(7, "Quantum technologies", a, "~$10 billion Projected market size of quantum-computing services in 2027, up from ~$400 million in 2020, growing at 50% per year",
      "Quantum computing services market", 2027, "market size of quantum-computing services", "~10", "USD billion", note=s + " Source on slide: IDC worldwide quantum computing forecast 2021–25."),
    T(8, "Trust architectures and digital identity", a,
      "Digital-trust technologies can reduce risk and potential negative impact from cyberattacks", "Digital trust and digital identity"),
    F(8, "Trust architectures and digital identity", a, "$101.5 billion Projected spending on service providers in digital trust by 2025",
      "Digital-trust services spending", 2025, "spending on service providers in digital trust", "101.5", "USD billion", note=s),
    F(8, "Trust architectures and digital identity", a, "3–13% Predicted economic benefits of digital identity by 2030, expressed as a share of GDP",
      "Digital identity economic value", 2030, "economic benefit of digital identity as share of GDP", "3–13", "percent of GDP", note=s),
    F(8, "Trust architectures and digital identity", a, "~$10.5 trillion Forecast costs and losses related to cybercrime by 2025, representing a 15% annual increase",
      "Cybercrime costs", 2025, "annual costs and losses related to cybercrime", "~10.5", "USD trillion", note=s),
    T(9, "Web3", a,
      "Web3 is based on a more decentralized, community-governed set of protocols that could represent a paradigm shift of authority and ownership to individuals with potentially far-reaching implications",
      "Web3"),
    T(10, "Future of bioengineering", b,
      "the future of bioengineering reflects the convergence of biological and information technologies to transform business and society",
      "Bioengineering"),
    F(10, "Future of bioengineering", b, "$2T–$4T Forecast annual global impact of bioengineering in 2030–40",
      "Bioengineering economic impact", 2040, "annual global economic impact of bioengineering", "2–4", "USD trillion per year", horizon="2030–40",
      note=s + " Range 2030-2040; target_year set to the end of the range. Source: McKinsey Global Institute, The Bio Revolution, May 2020."),
    T(11, "Future of clean energy", b,
      "The clean-energy future is a trend toward energy solutions that help achieve net-zero emissions across the energy value chain, from power generation or production to storage to distribution",
      "Clean energy"),
    F(11, "Future of clean energy", b, ">80% Share of 2050 global power demand that could be generated by renewable energy",
      "Renewable power share", 2050, "share of global power demand generated by renewables", ">80", "percent", note=s + " Source: McKinsey Global Energy Perspective 2022."),
    F(11, "Future of clean energy", b, "~30% CAGR Growth in battery demand by 2030, driven mainly by electrification of mobility applications",
      "Battery demand", 2030, "CAGR of battery demand", "~30", "percent per year", note=s),
    F(11, "Future of clean energy", b, "30−60% Decrease in battery prices expected by 2030",
      "Battery prices", 2030, "decrease in battery prices", "30–60", "percent", note=s),
    T(12, "Future of mobility", b,
      "Mobility is defined by several arenas across 4 disruptive dimensions of mobility (ACES) and adjacent technologies that enable more sustainable and efficient transportation",
      "Mobility (autonomous, connected, electric, shared)"),
    F(12, "Future of mobility", b, "Cost parity for small EVs with ICE today, with fuel-cell parity expected by 2030",
      "Fuel-cell vehicle cost parity", 2030, note=s),
    F(12, "Future of mobility", b, "50% Portion of miles traveled with shared transportation modes expected by 2030",
      "Shared mobility", 2030, "share of miles traveled with shared transportation modes", "50", "percent", note=s, conf="medium"),
    T(13, "Future of space technologies", b, "Moving down the cost curve has unlocked use cases that were previously cost-prohibitive",
      "Space technologies"),
    F(13, "Future of space technologies", b, ">10% estimated annual growth by 2030 in the space market from a value of ~$447B today",
      "Space economy", 2030, "annual growth of the space market", ">10", "percent per year",
      note=s + " Footnote cites Northern Sky Research projecting $1.25 trillion space-economy revenue by 2030; slide headline '>$1 trillion estimated market'."),
    F(13, "Future of space technologies", b, "~15% CAGR up to 2030 estimated for Earth observation information products, data analytics, data downlink, and space tourism and travel",
      "Earth observation and space services", 2030, "CAGR", "~15", "percent per year", note=s, conf="medium"),
    F(13, "Future of space technologies", b, ">1,400 companies involved in the new space industry, from governments to start-ups, which are expected to grow from 600+ today to 1,000+ in 2030",
      "Space industry participants", 2030, "number of companies (sub-group as printed)", "1,000+", "companies",
      note=s + " Slide column wording is ambiguous: >1,400 companies today and '600+ today to 1,000+ in 2030' for a sub-group.", conf="medium"),
    T(14, "Future of sustainable consumption", b,
      "Sustainable consumption centers on the use of goods and services that are produced with minimal environmental impact, using low-carbon and sustainable materials.",
      "Sustainable consumption"),
    F(14, "Future of sustainable consumption", b,
      "creating a $4 trillion–$6 trillion addressable market focused on industrial and individual end use by 2030",
      "Sustainability addressable market", 2030, "global sustainability addressable market", "4–6", "USD trillion"),
]

# ---------------------------------------------------------------- 2023
ai, dig, cc, eng, sus = "The AI revolution", "Building the digital future", "Compute and connectivity frontiers", "Cutting-edge engineering", "A sustainable world"
I23 = lambda i, j: inv("2023", i, j, "2022", "2021–22")
E["2023"] = [
    T(1, "Applied AI", ai,
      "With AI capabilities, such as machine learning (ML), computer vision, and natural-language processing (NLP), companies in all industries can use data and derive insights to automate processes, add or augment capabilities, and make better decisions.",
      "Applied AI", I23("$104 billion", "+6%")),
    T(2, "Industrializing machine learning", ai,
      "Industrializing machine learning (ML), commonly referred to as ML operations, or MLOps, refers to the engineering practices needed to scale and sustain ML applications in an enterprise.",
      "MLOps", I23("$3 billion", "+23%")),
    F(2, "Industrializing machine learning", ai, "IDC predicts that 60 percent of enterprises will have implemented MLOps by 2024.",
      "MLOps adoption", 2024, "share of enterprises that have implemented MLOps", "60", "percent", note="Attributed in the text to IDC."),
    T(3, "Generative AI", ai, "Generative AI marks a tipping point for AI.", "Generative AI",
      I23("$5 billion", "+44%") + " New trend in 2023."),
    F(3, "Generative AI", ai, "we anticipate significant growth across metrics in 2023.",
      "Generative AI momentum", 2023, note="From the 'Scoring the trend' text; metrics = interest, investment, innovation, talent as scored by the report."),
    F(3, "Generative AI", ai, "Hiring demand in 2023 will likely be significantly higher due to increased interest and investment.",
      "Generative AI talent demand", 2023, "job postings", note="Talent-market section."),
    T(4, "Next-generation software development", dig,
      "Adoption may be slow due to technical challenges, the need for large-scale retraining of developers and test engineers, and other organizational hurdles.",
      "Software development tooling (low-code, AI-assisted)", I23("$2 billion", "+29%") + " Opening sentence split across columns; second sentence quoted."),
    F(4, "Next-generation software development", dig,
      "By 2026, Gartner predicts that 80 percent of low- and no-code tool users will sit outside of traditional IT organizations.",
      "Low-code/no-code users", 2026, "share of low-/no-code tool users outside IT organizations", "80", "percent", note="Attributed in the text to Gartner."),
    T(5, "Trust architectures and digital identity", dig,
      "Digital-trust technologies enable organizations to manage technology and data risks, accelerate innovation, and protect assets.",
      "Digital trust and digital identity", I23("$47 billion", "+16%")),
    T(6, "Web3", dig,
      "Web3 goes beyond the typical understanding of cryptocurrency investments—it more significantly refers to a future model for the internet that decentralizes authority and redistributes it to users",
      "Web3", I23("$62 billion", "+40%")),
    T(7, "Advanced connectivity", cc,
      "Advanced-connectivity improvements will enhance user experiences for consumers worldwide and increase productivity in industries such as mobility, healthcare, and manufacturing.",
      "Advanced connectivity", I23("$118 billion", "+7%")),
    T(8, "Immersive-reality technologies", cc,
      "Immersive-reality technologies use spatial computing to interpret physical space; simulate the addition of data, objects, and people to real-world settings; and enable interactions in virtual worlds",
      "Immersive reality (AR/VR/MR)", I23("$16 billion", "+10%")),
    F(8, "Immersive-reality technologies", cc,
      "Our research suggests that the emerging metaverse could generate up to $4 trillion to $5 trillion in value across consumer and enterprise use cases by 2030.",
      "Metaverse value", 2030, "value generated by the metaverse", "4–5", "USD trillion"),
    F(8, "Immersive-reality technologies", cc,
      "New VR headsets are also expected throughout 2023, and peripheral devices (for example, haptics and displays) continue to advance",
      "VR headsets", 2023),
    T(9, "Cloud and edge computing", cc,
      "In the future, enterprises will leverage an infrastructure footprint that involves compute and storage at multiple location points, from on-premises to closer-to-premises (the edge) and from small regional data centers to remote hyperscale data centers.",
      "Cloud and edge computing", I23("$84 billion", "+12%")),
    T(10, "Quantum technologies", cc,
      "Quantum technologies promise to take advantage of the unique properties of quantum mechanics to perform specific types of complex calculations exponentially more efficiently than classical computers",
      "Quantum technologies", I23("$2 billion", "+12%")),
    T(11, "Future of mobility", eng,
      "More than a century after mass production of automobiles began, mobility has arrived at a second great inflection point: a shift toward autonomous driving, connectivity, the electrification of vehicles, and shared-mobility (ACES) technologies.",
      "Mobility (autonomous, connected, electric, shared)", I23("$194 billion", "+15%")),
    F(11, "Future of mobility", eng, "autonomous-driving technologies are projected to create up to $400 billion in revenue by 2035.",
      "Autonomous-driving revenue", 2035, "revenue from autonomous-driving technologies", "up to 400", "USD billion"),
    F(11, "Future of mobility", eng,
      "Meanwhile, market size estimates for the micromobility and minimobility industries advanced to $440 billion and $100 billion by 2030, respectively.",
      "Micromobility market", 2030, "micromobility market size", "440", "USD billion", note="Same sentence: minimobility $100 billion by 2030. Footnote marker removed from quote."),
    F(11, "Future of mobility", eng, "the global automotive software market is also expected to grow rapidly at a 5.5 percent CAGR from 2019 to 2030.",
      "Automotive software market", 2030, "CAGR of global automotive software market 2019–2030", "5.5", "percent per year"),
    T(12, "Future of bioengineering", eng,
      "Breakthroughs in biology, combined with innovations in digital technology, could help organizations respond to demands in areas as diverse as healthcare, food and agriculture, consumer products, sustainability, and energy and materials production by creating new products and services.",
      "Bioengineering", I23("$43 billion", "–19%")),
    F(12, "Future of bioengineering", eng,
      "McKinsey research suggests that 400 use cases for bioengineering, almost all of which are scientifically feasible today, could have an economic impact of $2 trillion to $4 trillion per year from 2030 to 2040.",
      "Bioengineering economic impact", 2040, "annual economic impact of bioengineering use cases", "2–4", "USD trillion per year", horizon="2030 to 2040",
      note="A page header ('Future of bioengineering') interrupts the sentence in the PDF text and is omitted. Range 2030-2040; target_year is the end of the range. Same figure as 2022."),
    F(12, "Future of bioengineering", eng,
      "Present estimates suggest that cultivated meat could provide 0.5 percent of the world’s meat supply by 2030, representing billions of pounds of meat and up to $25 billion in revenue.",
      "Cultivated meat", 2030, "share of world meat supply from cultivated meat", "0.5", "percent", note="Same sentence: up to $25 billion revenue."),
    T(13, "Future of space technologies", eng,
      "The most significant development for the space industry in the past five to ten years has been decreasing technology costs, which are making new capabilities and applications more accessible.",
      "Space technologies", I23("$8 billion", "+16%")),
    F(13, "Future of space technologies", eng, "analysis suggests that the space market could exceed $1 trillion by 2030.",
      "Space economy", 2030, "space market size", ">1", "USD trillion"),
    F(13, "Future of space technologies", eng,
      "Several new highly anticipated launch vehicles are expected to debut in 2023 and 2024, including the SpaceX’s superheavy Starship, designed to carry larger loads; the Vulcan Centaur, from United Launch Alliance, which is designed to carry satellites into orbit; and Blue Origin’s New Glenn",
      "New heavy launch vehicles", 2024, horizon="2023 and 2024", note="Vehicles named: Starship, Vulcan Centaur, New Glenn."),
    T(14, "Electrification and renewables", sus,
      "Electrification and renewables help drive toward net-zero commitments and include solar-, wind-, and hydro-powered renewables and other renewables; nuclear energy; hydrogen; sustainable fuels; and electric-vehicle charging.",
      "Electrification and renewable energy", I23("$288 billion", "+27%") + " Short profile (one page shared with trend 15); footnote: capex-related investments for 2022 totaled $578 billion."),
    T(15, "Climate technologies beyond electrification and renewables", sus,
      "Climate technologies include carbon capture, utilization, and storage (CCUS); carbon removals; natural climate solutions; circular technologies; alternative proteins and agriculture; water and biodiversity solutions and adaptation; and technologies to track net-zero progress.",
      "Climate technologies (CCUS, carbon removal, circularity)", I23("$86 billion", "+8%") + " Short profile; footnote: capex-related investments for 2022 totaled $98 billion."),
]

# ---------------------------------------------------------------- 2024
I24 = lambda i, j: inv("2024", i, j, "2023", "2022–23")
E["2024"] = [
    T(1, "Generative AI", ai,
      "Generative AI (gen AI) has been making significant strides, pushing the boundaries of machine capabilities.",
      "Generative AI", I24("$36 billion", "+111%")),
    F(1, "Generative AI", ai,
      "As we progress through 2024 and beyond, we anticipate organizations investing in the risk mitigation, operating model, talent, and technological capabilities required to scale gen AI.",
      "Generative AI enterprise investment", 2024),
    T(2, "Applied AI", ai,
      "As we navigate through 2024, the impact of analytical AI technologies, including applications of machine learning (ML), computer vision, and natural-language processing (NLP), continues to grow across all sectors.",
      "Applied AI", I24("$86 billion", "–29%")),
    T(3, "Industrializing machine learning", ai,
      "Industrializing machine learning (ML), also known as machine learning operations (MLOps), is the process of scaling and maintaining ML applications within enterprises.",
      "MLOps", I24("$3 billion", "–36%")),
    T(4, "Next-generation software development", dig,
      "The landscape of software development is currently experiencing a transformative shift, driven by an influx of cutting-edge technologies such as generative AI (gen AI) and cloud-native architectures.",
      "Software development tooling (low-code, AI-assisted)", I24("$17 billion", "–37%")),
    T(5, "Digital trust and cybersecurity", dig,
      "Digital trust and cybersecurity enable organizations to manage technology and data risks, accelerate innovation, and protect assets.",
      "Digital trust and cybersecurity", I24("$34 billion", "–34%") + " Renamed from 'Trust architectures and digital identity' (2022-2023)."),
    T(6, "Advanced connectivity", cc,
      "Advanced-connectivity technologies can potentially revolutionize the experiences of consumers and industries such as mobility, manufacturing, and agriculture.",
      "Advanced connectivity", I24("$29 billion", "–24%")),
    T(7, "Immersive-reality technologies", cc,
      "Immersive-reality technologies allow users to experience an augmented form of our world or virtual worlds while uncovering a series of new use cases for consumers and enterprises alike.",
      "Immersive reality (AR/VR/MR)", I24("$6 billion", "–36%")),
    T(8, "Cloud and edge computing", cc,
      "Cloud and edge computing has amplified AI capabilities for both training and inferencing on foundational models and will continue to be a major driver for the adoption of these technologies.",
      "Cloud and edge computing", I24("$54 billion", "–38%") + " Opening sentence split across columns; a later sentence is quoted."),
    F(8, "Cloud and edge computing", cc,
      "The rise of AI in 2023 resulted in a massive increase in cloud and edge usage, with a CAGR of approximately 30.9 percent expected in the cloud AI market between 2023 and 2030",
      "Cloud AI market", 2030, "CAGR of the cloud AI market 2023–2030", "~30.9", "percent per year", note="Footnote cites Fortune Business Insights (cloud AI market) and Gartner."),
    F(8, "Cloud and edge computing", cc,
      "While 2023 was mostly focused on training foundation models for AI, companies are expected to begin performing inference at scale on their models in 2024.",
      "AI inference at scale", 2024),
    T(9, "Quantum technologies", cc,
      "In 2023, we saw steady progress on both the hardware and software fronts while organizations took more practical steps to ensure that their infrastructure and security are ready for the technology.",
      "Quantum technologies", I24("$1 billion", "–17%") + " Opening sentence split across columns; a later sentence is quoted."),
    T(10, "Future of robotics", eng,
      "From a technological perspective, AI has led to many innovations that have increased the capabilities and accelerated the training of physical robots.",
      "Robotics", I24("$6 billion", "–20%") + " New trend in 2024. Opening sentence split across columns; a later sentence is quoted."),
    T(11, "Future of mobility", eng,
      "Technical advancements, coupled with rising sustainability concerns, have given rise to a new era of mobility.",
      "Mobility (autonomous, connected, electric, shared)", I24("$83 billion", "–5%")),
    F(11, "Future of mobility", eng,
      "approximately 30 battery factories are currently planned, being constructed, or operational in the United States alone; 13 of them are expected to open by 2025.",
      "US battery factories", 2025, "US battery factories open", "13", "factories"),
    F(11, "Future of mobility", eng, "The year 2024 could be a watershed one for autonomous trucking as companies begin larger-scale on-the-road pilots.",
      "Autonomous trucking", 2024),
    T(12, "Future of bioengineering", eng,
      "The combination of biological and computing advancements has led to a range of innovations in products and services for industries such as healthcare, food and agriculture, consumer products, sustainability, and energy and materials.",
      "Bioengineering", I24("$62 billion", "–23%")),
    T(13, "Future of space technologies", eng,
      "Rapidly decreasing technology costs over the past decade have given rise to an increase in the viability and relevance of space technologies.",
      "Space technologies", I24("$9 billion", "–9%")),
    F(13, "Future of space technologies", eng,
      "Revenues of the industry’s “backbone”—that is, space hardware and service providers—could potentially grow to more than $750 billion by 2035",
      "Space industry backbone revenue", 2035, "revenue of space hardware and service providers", ">750", "USD billion"),
    T(14, "Electrification and renewables", sus,
      "Electrification and renewable-energy technologies are crucial for reducing global carbon emissions in accordance with the Paris Agreement.",
      "Electrification and renewable energy", I24("$183 billion", "+1%")),
    F(14, "Electrification and renewables", sus,
      "McKinsey research estimates that climate technology value chains will require approximately 200 million skilled workers globally by 2050.",
      "Climate technology workforce", 2050, "skilled workers required by climate technology value chains", "~200", "million workers",
      note="A requirement estimate rather than an outcome forecast; kept because it names a year and a number."),
    T(15, "Climate technologies beyond electrification and renewables", sus,
      "Climate technologies beyond electrification and renewables cover technologies related to circularity and resources and carbon capture and removal.",
      "Climate technologies (CCUS, carbon removal, circularity)", I24("$68 billion", "–11%")),
]

# ---------------------------------------------------------------- 2025
ai5, cc5, eng5 = "AI revolution", "Compute and connectivity frontiers", "Cutting-edge engineering"
I25 = lambda i, j: inv("2025", i, j, "2024", "2023–24")
E["2025"] = [
    T(1, "Agentic AI", ai5,
      "Agentic AI is an artificial intelligence system capable of independently planning and executing complex, multistep tasks.",
      "Agentic AI", I25("$1.1 billion", "+985%") + " New trend in 2025."),
    T(2, "Artificial intelligence", ai5,
      "Artificial intelligence refers to computer systems designed to perform tasks that typically require human intelligence.",
      "Artificial intelligence", I25("$124.3 billion", "+35%") + " Per the report, an overarching artificial intelligence category replaces applied AI, generative AI, industrializing machine learning, and next-generation software development (2024 trends)."),
    F(2, "Artificial intelligence", ai5,
      "Gartner projects that by 2027, 40 percent of gen AI solutions will be multimodal, up from just 1 percent in 2023.",
      "Multimodal generative AI", 2027, "share of gen AI solutions that are multimodal", "40", "percent", note="Attributed in the text to Gartner."),
    F(2, "Artificial intelligence", ai5,
      "Google parent Alphabet, Amazon, Meta, and Microsoft are each projected to spend $70 billion to more than $100 billion on AI-related capital expenditures in 2025",
      "Hyperscaler AI capital expenditure", 2025, "AI-related capex per company", "70 to >100", "USD billion", note="Footnote cites CNBC and Reuters."),
    T(3, "Application-specific semiconductors", cc5,
      "Application-specific semiconductors are purpose-built chips optimized to perform specialized tasks.",
      "Application-specific semiconductors", I25("$7.5 billion", "+22%") + " New trend in 2025."),
    F(3, "Application-specific semiconductors", cc5,
      "McKinsey analysis suggests that, in a midrange scenario, demand for AI-ready data center capacity will rise at an average rate of 33 percent a year between 2023 and 2030.",
      "AI data center capacity demand", 2030, "annual growth of demand for AI-ready data center capacity", "33", "percent per year", note="Midrange scenario."),
    F(3, "Application-specific semiconductors", cc5,
      "This means that about 70 percent of total demand for data center capacity will be for data centers equipped to host workloads from AI systems by 2030.",
      "AI share of data center demand", 2030, "share of data center capacity demand that is AI-ready", "~70", "percent", note="Midrange scenario (previous sentence)."),
    F(3, "Application-specific semiconductors", cc5,
      "A global shortage of skilled semiconductor workers that could lead to a significant shortfall by 2030 is delaying production and threatening supply chain stability.",
      "Semiconductor talent shortage", 2030),
    T(4, "Advanced connectivity", cc5,
      "Advanced connectivity has continued to grow across interest and innovation metrics from 2023 to 2024 and is a leader among the trends for number of patents granted.",
      "Advanced connectivity", I25("$44.2 billion", "–14%") + " Quote from 'Scoring the trend'; the definition sentence was not cleanly extractable."),
    F(4, "Advanced connectivity", cc5,
      "The global network-slicing market, which provides specific performance characteristics across each slice of a network, is projected to reach $1.69 billion in 2025, an increase of 49.6 percent compared with $1.13 billion in 2024.",
      "Network slicing market", 2025, "global network-slicing market", "1.69", "USD billion"),
    F(4, "Advanced connectivity", cc5,
      "Market size is projected to increase from $6.27 billion in 2024 to $32.86 billion by 2032, a CAGR of 23 percent.",
      "Private wireless network market", 2032, "market size", "32.86", "USD billion",
      note="The sentence does not name the market; surrounding text is about private wireless/private 5G networks.", conf="medium"),
    F(4, "Advanced connectivity", cc5,
      "North America is at the forefront, with 77 percent population coverage and an expected 89 percent adoption rate by 2030",
      "5G adoption in North America", 2030, "5G adoption rate in North America", "89", "percent"),
    T(5, "Cloud and edge computing", cc5,
      "Cloud and edge computing involve distributing workloads across locations, from hyperscale remote data centers to regional hubs and local nodes.",
      "Cloud and edge computing", I25("$80.8 billion", "+2%")),
    F(5, "Cloud and edge computing", cc5, "hyperscale data center capacity is projected to triple by 2030",
      "Hyperscale data center capacity", 2030, "hyperscale data center capacity multiple", "3", "times current"),
    F(5, "Cloud and edge computing", cc5,
      "McKinsey analysis suggests that global demand for data center capacity could rise 19 to 22 percent annually from 2023 to 2030, more than tripling current demand and reaching 171 to 219 gigawatts a year.",
      "Data center capacity demand", 2030, "global data center capacity demand", "171–219", "GW"),
    T(6, "Immersive-reality technologies", cc5,
      "Immersive-reality technologies encompass augmented reality (AR) and virtual reality (VR) and include AR smart glasses, advanced haptic feedback, and AI-powered enhancements that improve rendering, tracking, and processing capabilities.",
      "Immersive reality (AR/VR/MR)", I25("$6 billion", "–11%")),
    F(6, "Immersive-reality technologies", cc5,
      "The AR/VR market saw steady but modest growth in 2024, with headset shipments increasing by 10 percent, though forecasts suggest growth may slow in 2025.",
      "AR/VR headset market", 2025, note="Footnote cites Neowin."),
    T(7, "Digital trust and cybersecurity", cc5,
      "Digital trust and cybersecurity covers technologies and practices designed to ensure secure, transparent, and trustworthy digital interactions.",
      "Digital trust and cybersecurity", I25("$77.8 billion", "+7%")),
    T(8, "Quantum technologies", cc5,
      "Quantum-based technologies make use of the unique properties of quantum mechanics to execute certain complex calculations exponentially faster than classical computers",
      "Quantum technologies", I25("$2 billion", "–15%")),
    T(9, "Future of robotics", eng5,
      "The future of robotics covers the advancement of robotics capable of performing tasks autonomously or semiautonomously",
      "Robotics", I25("$7 billion", "–2%")),
    F(9, "Future of robotics", eng5,
      "The market opportunity is massive—up to approximately $900 billion by 2040",
      "AI-driven robotics market", 2040, "market opportunity", "up to ~900", "USD billion",
      note="From a quoted statement by a McKinsey partner printed in the edition (person not named here)."),
    T(10, "Future of mobility", eng5,
      "Mobility technologies include autonomous vehicles, electric vehicles, drones, urban air mobility solutions, such as electric vertical takeoff and landing aircraft, and micromobility",
      "Mobility (autonomous, connected, electric, shared)", I25("$131.6 billion", "+6%")),
    F(10, "Future of mobility", eng5,
      "Unit costs are expected to lower significantly by 2035, as companies achieve greater vehicle utilization, make operational improvements, and reduce R&D needs.",
      "Autonomous vehicle unit costs", 2035, note="Context: autonomous-vehicle adoption timeline slipped by two to three years."),
    F(10, "Future of mobility", eng5, "Delivery drone services are expected to reach $29 billion by 2034, a CAGR of 40 percent.",
      "Drone delivery market", 2034, "delivery drone services market", "29", "USD billion", note="Footnote cites Polaris Market Research."),
    T(11, "Future of bioengineering", eng5,
      "Bioengineering is the application of engineering principles to biology, utilizing technological advancements (for example, gene editing, synthetic biology) to improve health and human performance, transform food value chains, and create innovative offerings.",
      "Bioengineering", I25("$57.3 billion", "–17%")),
    T(12, "Future of space technologies", eng5,
      "Space technologies cover satellite systems, launch vehicles, habitation modules, and exploration missions",
      "Space technologies", I25("$9.3 billion", "–9%")),
    T(13, "Future of energy and sustainability technologies", eng5,
      "Energy and sustainability technologies encompass a broad spectrum of innovations aimed at transforming the global energy landscape toward a more sustainable and resilient future.",
      "Energy and sustainability technologies", I25("$223.2 billion", "–6%") + " Merges 2024's electrification and renewables and climate technologies beyond electrification and renewables."),
    F(13, "Future of energy and sustainability technologies", eng5,
      "Depending on decarbonization pathways, policy support, and the pace of technological progress, nuclear power could account for anywhere from 8 to 43 percent of global electricity by 2040",
      "Nuclear power share", 2040, "nuclear share of global electricity", "8–43", "percent", note="Same sentence: market revenues potentially reaching $400 billion under the most optimistic scenarios."),
    F(13, "Future of energy and sustainability technologies", eng5,
      "India is scaling its production capacity and is expected to become the second-largest solar PV manufacturer by 2026.",
      "Solar PV manufacturing in India", 2026, "India's rank among solar PV manufacturers", "2", "rank"),
]

# ---------------------------------------------------------------- 2026 (web page only)
p = "Label from the exhibit description on the publisher's web page; the 143-page PDF was not readable, so printed order and section are unknown. rank is null; entries follow the exhibit description's order."
E["2026"] = [
    T(None, "Future of energy and sustainability technologies", None,
      "Future of energy and sustainability technologies sits in the upper-right area with high innovation and high interest, and has the largest bubble (highest equity investment).",
      "Energy and sustainability technologies", p + " Page: energy technologies drew nearly $200 billion in investment in 2025."),
    T(None, "AI infrastructure and model architectures", None,
      "Last year’s AI trend is now AI infrastructure and model architectures to more accurately reflect the foundational technologies that underpin AI.",
      "AI infrastructure and model architectures", p + " Renamed from 2025 'Artificial intelligence'."),
    T(None, "Advanced connectivity", None,
      "Advanced connectivity and future of life sciences and bioengineering score high on innovation (above 0.7) but lower on interest.",
      "Advanced connectivity", p),
    T(None, "Future of life sciences and bioengineering", None,
      "last year’s future of bioengineering is now future of life sciences and bioengineering, which more fully reflects advances across the life sciences spectrum.",
      "Bioengineering", p + " Renamed from 'Future of bioengineering'."),
    T(None, "Cybersecurity and trustworthy systems", None,
      "Last year’s digital trust and cybersecurity is now cybersecurity and trustworthy systems, highlighting how advances in AI require security to be continually woven into integrated hardware and software systems.",
      "Digital trust and cybersecurity", p + " Renamed from 'Digital trust and cybersecurity'."),
    T(None, "Application-specific semiconductors", None,
      "Cybersecurity and trustworthy systems and application-specific semiconductors sit in the middle range for both dimensions.",
      "Application-specific semiconductors", p),
    T(None, "Agentic AI", None, "Agentic AI is becoming the connective tissue of the enterprise", "Agentic AI", p),
    T(None, "Agentic software development", None,
      "Two newly highlighted trends join this year’s report: agentic software development and AI for scientific discovery and engineering.",
      "Agentic software development", p + " New trend in 2026."),
    T(None, "AI for scientific discovery and engineering", None,
      "Two newly highlighted trends join this year’s report: agentic software development and AI for scientific discovery and engineering.",
      "AI for scientific discovery and engineering", p + " New trend in 2026."),
    T(None, "Quantum technologies", None,
      "quantum computing continues to advance, giving a glimpse into how it could soon solve problems that would otherwise be infeasible.",
      "Quantum technologies", p),
    T(None, "Immersive-reality technologies", None,
      "Robotics, mobility, and immersive-reality technologies are converging to reshape how humans interact with digital and physical systems.",
      "Immersive reality (AR/VR/MR)", p),
    T(None, "Future of mobility", None, "Future of mobility has moderate interest but low innovation, with a relatively large bubble.",
      "Mobility (autonomous, connected, electric, shared)", p),
    T(None, "Future of robotics", None,
      "AI has become an accelerant in robotics, creating a new class of autonomous bots capable of interacting with the world around them.",
      "Robotics", p),
    T(None, "Future of space technologies", None,
      "Future of robotics and future of space technologies score low on both axes with small bubbles.",
      "Space technologies", p),
    F(None, "Equity investment across trends", None,
      "Five of the trends—agentic software development, AI infrastructure and model architectures, AI for scientific discovery and engineering, the future of space technologies, and the future of robotics—are on track to receive more than double the investment in 2026 compared with 2025",
      "Equity investment in five frontier trends", 2026, "equity investment 2026 vs 2025", ">2", "times",
      note="Extrapolated by the publisher from first-half 2026 investment. Applies to each of the five trends named."),
    F(None, "Equity investment across trends", None,
      "all trends, except advanced connectivity, are on track to generate higher year-over-year funding totals.",
      "Equity investment across trends", 2026, "year-over-year equity investment change", ">0", "direction",
      note="Extrapolated from first-half 2026. Implies 13 of 14 trends up year over year in 2026."),
    F(None, "AI data center power demand", None,
      "US data centers running AI workloads alone are projected to consume as much electricity by 2030 as California does today.",
      "AI data center electricity use", 2030, note="Footnote cites McKinsey, 'The next big shifts in AI workloads and hyperscaler strategies', December 17, 2025."),
]

TEXT = {
    "2021": "tto-2021.txt", "2022": "tto-2022.txt", "2023": "tto-2023.raw.txt",
    "2024": "tto-2024.raw.txt", "2025": "tto-2025.raw.txt", "2026": "p2026.txt",
}
RAW2 = {"2022": "tto-2022.raw.txt", "2021": "tto-2021.txt"}

META = {
    "2021": dict(published="2021-06", title="The top trends in tech (executive summary)", status="complete",
                 notes="First edition (2025 report calls itself the fifth edition; 2026 the sixth). Published June 2021 as an online interactive ('The top trends in tech') plus an 18-slide executive-summary PDF; the interactive is JavaScript-rendered and was not read. 10 trends: 7 industry-agnostic, 3 industry-specific. No equity-investment, job-posting or adoption figures per trend (momentum score only, in charts). Forecast entries are the dated figures on slide 7 'Effects of technology trends up to 2050'. rank = trend number as printed; forecast entries carry their trend's rank."),
    "2022": dict(published="2022-08", title="McKinsey Technology Trends Outlook 2022", status="complete",
                 notes="184-page full report (research overview plus 14 trend profiles, slide format). Two groups: Silicon Age and Engineering Tomorrow. Per-trend investment and adoption appear only in the bubble exhibit (no figures in text), so trend notes carry none. Forecast entries are dated figure labels from each profile's 'Why should leaders pay attention?' slides; several reconstructed from multi-column layout (see notes). Many cite third parties (IDC, Gartner, NSR) as listed on the slide. rank = order on the 'Trends at a glance' page; forecast entries carry their trend's rank."),
    "2023": dict(published="2023-07", title="Technology Trends Outlook 2023", status="complete",
                 notes="81-page report, 15 trends in five groups. Equity investment (2022, $ billion) and job-postings change (2021–22) are printed per trend and recorded in each trend's note. Adoption score (0-5) is shown only graphically and is not recorded. The 2023-v5 PDF snapshot of 2024-09-14 is truncated (1 MB); the 2025-02-01 snapshot is complete. rank = contents order; forecast entries carry their trend's rank."),
    "2024": dict(published="2024-07", title="Technology Trends Outlook 2024", status="complete",
                 notes="100-page report, 15 trends in five groups. Equity investment (2023, $ billion) and job-postings change (2022–23) per trend in notes. Adoption score (1-5, 2023) is graphical only and not recorded. rank = contents order; forecast entries carry their trend's rank."),
    "2025": dict(published="2025-07", title="Technology Trends Outlook 2025", status="complete",
                 notes="108-page report, 'Fifth edition', 13 numbered trends in three groups. Equity investment (2024) and job-postings change (2023–24) per trend in notes. Adoption score graphical only, not recorded. rank = printed trend number; forecast entries carry their trend's rank."),
    "2026": dict(published="2026-09-15", title="McKinsey technology trends outlook 2026", status="partial",
                 notes="Sixth edition, 143-page PDF, published 2026-09-15 (datePublished on the web page). The PDF is not in the Wayback Machine and mckinsey.com refuses scripted and WebFetch access, so only the web article (Wayback snapshot 2026-09-15) was read. It names all 14 trends and three groups (AI revolution, compute and connectivity frontiers, cutting-edge engineering) but not the printed order or the group of each trend, and gives no per-trend investment, job-posting or adoption figures. rank is null throughout; trend entries follow the order of the page's exhibit description. Forecast entries are from the page's own text."),
}


def main():
    bad = 0
    OUT.mkdir(parents=True, exist_ok=True)
    for ed, entries in E.items():
        txt = norm((HERE / TEXT[ed]).read_text(errors="ignore"))
        alt = norm((HERE / RAW2[ed]).read_text(errors="ignore")) if ed in RAW2 else ""
        rows = []
        for e in entries:
            q = e["quote"]
            assert len(q) <= 400, (ed, q)
            found = norm(q) in txt or norm(q) in alt
            if not found:
                bad += 1
                print(f"NOT VERBATIM {ed} [{e['label']}]: {q[:90]}")
            row = {k: v for k, v in e.items() if v is not None or k in ("rank", "section")}
            row["source_url"] = URL[ed]
            rows.append(row)
        m = META[ed]
        doc = {"edition": ed, "published": m["published"], "status": m["status"],
               "sources": [URL[ed], WAYBACK[ed]], "publisher": PUB, "series": SERIES, "title": m["title"],
               "trend_count": sum(1 for r in rows if r["kind"] == "trend"),
               "forecast_count": sum(1 for r in rows if r["kind"] == "forecast"),
               "notes": m["notes"], "entries": rows}
        (OUT / f"{ed}.json").write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
        print(ed, len(rows), "entries", doc["trend_count"], "trends", doc["forecast_count"], "forecasts")
    print("not verbatim:", bad)


if __name__ == "__main__":
    main()
