"""Hindsight's own labels for each IDC prediction: (subject, metric, overrides).

Keyed by IDC document number (or a local key for non-IDC-hosted copies).
The order follows IDC's prediction numbers 1 to 10. `overrides` can set
value, unit, target_year or note when the automatic parse is wrong.
"""

A = {
    # ---------------- IT Industry ----------------
    "US53858725": [  # IT Industry 2026
        ("Composite AI adoption", "share of organizations adopting composite AI", {}),
        ("AI agent use in the G2000", "growth in G2000 agent use", {"value": "10", "unit": "x", "note": "Also: token/call loads 1,000x."}),
        ("Agents as IT interface", "share of IT product and services interactions using agents as primary interface", {}),
        ("AI-human collaboration metrics", "margin advantage of organizations measuring AI-human collaboration", {"value": "up to 15", "unit": "% higher margins"}),
        ("Modular IT services", "share of global IT services delivered as modular, platform-enabled products", {}),
        ("Cloud modernization for AI", "share of organizations modernizing legacy cloud for AI workloads", {}),
        ("Data clean rooms and exchanges", "share of enterprises collaborating on data via private exchanges or clean rooms", {}),
        ("Quantum-accelerated supercomputing", "share of complex defense and science problems solved with quantum-accelerated supercomputing (US, EU, China governments)", {}),
        ("LEO satellite connectivity", "share of enterprises adopting LEO satellite connectivity", {}),
        ("Edge AI inference", "share of enterprise AI inference processed on endpoints or edge nodes", {}),
    ],
    "US51736824": [  # IT Industry 2025
        ("AI economics models", "share of G1000 adopting value-based AI economics models", {}),
        ("GenAI investment pullback", "share of organizations reducing GenAI investments", {}),
        ("Cyber-recovery and high availability", "share of CIOs adopting unified cyber-recovery and HA practices", {}),
        ("Cloud architecture modernization", "share of businesses that modernized up to 50% of cloud architecture", {"value": "more than 60"}),
        ("Data-as-a-product architectures", "share of large enterprises where data-as-a-product breaks down silos", {"value": "50"}),
        ("Enterprise AI agents", "share of organizations using function-specific enterprise agents", {}),
        ("Diversified AI inferencing", "share of enterprises requiring diversified inferencing delivery", {}),
        ("Sustainable AI frameworks", "share of enterprises implementing sustainable AI frameworks", {}),
        ("Unified AI platforms", "share of enterprise composite AI apps built on a unified platform framework", {}),
        ("AI and job roles", "share of IT and LOB job roles redefined or eliminated", {}),
    ],
    "US50435423": [  # IT Industry 2024
        ("AI share of IT spend", "share of G2000 core IT spend allocated to AI initiatives", {"value": "over 40"}),
        ("Tech provider AI investment", "share of tech provider R&D, staffing and capex allocated to AI/automation", {}),
        ("Infrastructure cost uncertainty", None, {"value": None, "unit": None, "note": "No number; applies to all enterprises."}),
        ("Provider data portfolios", None, {"value": None, "unit": None}),
        ("Skills underfunding", "share of enterprises prevented from achieving full value from AI, cloud, data and security", {}),
        ("GenAI-enabled services delivery", "share of service engagements including GenAI-enabled delivery", {}),
        ("AI-enabled control platforms", "share of infrastructure, security, data and apps relying on advanced control platforms", {"note": "Also: only half of enterprises will use them effectively."}),
        ("AI-integrated IT products", "share of new IT brands/products for underserved segments based on integrated AI services", {"value": "100", "unit": "% (all)"}),
        ("Customer-created experience journeys", "share of F500 firms enabling customers to create their own journeys", {}),
        ("LEO satellite connectivity", "share of enterprises integrating LEO satellite connectivity", {}),
    ],
    "US49563122": [  # IT Industry 2023
        ("IT budgets for as-a-service assets", "share of IT budgets in G500 enterprises allotted to assets for own as-a-service processes and smart products", {"value": "over 50"}),
        ("Cloud-based control platforms", "share of infrastructure, security, data and network offerings requiring cloud-based control platforms", {}),
        ("IT skills shortfall", "share of businesses prevented from full value from cloud, data and automation", {}),
        ("Digital sovereignty", "share of IT and data assets for which G2000 CIOs shift staff, budgets and processes", {"value": "more than 35"}),
        ("As-a-service adoption barriers", "share of enterprises whose aaS adoption is curbed more by inability to assess promises than by cost", {}),
        ("SME teams bundled in aaS offerings", "share of platinum-level aaS offerings including specialized SME teams", {}),
        ("Silicon and code supply chain delays", "number of high-visibility digital product launches facing major delays", {"value": "20", "unit": "launches"}),
        ("Tech-by-wire control silos", "share of enterprises struggling with siloed control systems", {}),
        ("Trust in autonomous systems", "share of G2000 enterprises facing material risks from distrust of autonomous tech", {}),
        ("Machine vision", None, {"value": None, "unit": None, "note": "No number beyond 'five fastest-growing enterprises in most industries'."}),
    ],
    "US48312921": [  # IT Industry 2022
        ("As-a-service spending shift", "share of tech and services spending shifted to as-a-service and outcomes-centric models", {}),
        ("Cloud provider selection", "share of G2000 resetting cloud selection processes to business outcomes", {}),
        ("AI-assisted cloud governance", "share of enterprises using AI-assisted, cloud-linked governance services", {"note": "Also: 70% will not achieve full value due to skills mismatches."}),
        ("As-a-service bundles", "share of large enterprises' IT budgets redistributed by integrated aaS bundles", {}),
        ("IT spend for mandated transitions", "multiple of IT spend by industry leaders facing mandated transitions", {"value": "3", "unit": "x (triple)", "note": "Also: need 6x gains in IT operational efficiency."}),
        ("Augmentation vs automation returns", "returns on augmenting investments relative to automating ones, for 70% of G2000", {"value": "2", "unit": "x", "note": "70% of G2000."}),
        ("Data governance restructuring", "share of enterprises restructuring data governance", {}),
        ("In-person experience modernization", "share of G2000 shifting half of new hardware/connectivity spend to in-person experiences", {}),
        ("Digital sustainability teams", "share of G2000 with digital sustainability teams", {}),
        ("Data controls and valuation", None, {"value": None, "unit": None}),
    ],
    "US46942020": [  # IT Industry 2021
        ("Cloud-centric shift after the pandemic", "share of enterprises with a mechanism to shift to cloud-centric infrastructure twice as fast", {}),
        ("Edge investments", "share of edge-driven investments accelerated by pandemic workforce and operations changes", {}),
        ("Hybrid workforce technical parity", "share of G2000 companies committing to technical parity for a hybrid workforce", {}),
        ("Pandemic technical debt", "share of CIOs shadowed by pandemic technical debt", {}),
        ("Digital resiliency", "speed advantage of digital-resiliency-focused enterprises in adapting to disruption", {"value": "50", "unit": "% faster"}),
        ("Cloud ecosystem for automation", None, {"value": None, "unit": None}),
        ("AI start-up acquisitions", "share of G2000 companies acquiring at least one AI software start-up", {"value": "25", "unit": "% (one-quarter)"}),
        ("Supplier and partner relationships", "share of enterprises overhauling supplier, provider and partner relationships", {}),
        ("Sustainable IT supply chains", "share of G2000 companies mandating reusable materials, carbon neutrality and lower energy use from IT providers", {}),
        ("Hybrid workforce and automation failures", "share of enterprises' hybrid workforce and business automation efforts delayed or failed", {"value": "50", "unit": "% (half)"}),
    ],
    "IT2020deck": [  # IT Industry 2020
        ("Digital transformation share of ICT spending", "share of ICT spending directly for digital transformation and innovation", {"value": "over 50"}),
        ("Hybrid/multicloud management", "share of enterprises integrating cloud management across public and private clouds", {}),
        ("Edge infrastructure", "share of new enterprise IT infrastructure deployed at the edge", {"value": "over 50", "note": "Also: by 2024, apps at the edge increase 800%."}),
        ("Enterprises as software producers", "share of enterprises that are prolific software producers", {"value": "nearly 67", "unit": "% (nearly two-thirds)"}),
        ("Cloud-native apps", "number of digital apps and services developed with cloud-native approaches", {"value": "over 500 million", "unit": "apps and services"}),
        ("AI in enterprise apps", "share of new enterprise apps embedding AI", {"value": "at least 90", "note": "Also: by 2024, over 50% of UI interactions use AI-enabled vision, speech, NLP, AR/VR."}),
        ("Chief Trust Officer", "share of G2000 naming a Chief Trust Officer", {}),
        ("Enterprise developer ecosystems", "share of G2000 with a digital developer ecosystem", {}),
        ("Cross-industry offerings", "share of revenue growth from white-space cross-industry offerings", {}),
        ("Cloud megaplatform concentration", "market share of the top 5 public cloud megaplatforms", {"value": "at least 75"}),
    ],
    "US44403818": [  # IT Industry 2019
        ("Digitized global GDP", "share of global GDP digitized", {"value": "60+", "note": "Also: almost $7 trillion IT-related spending 2019-2022."}),
        ("3rd Platform share of IT spending", "share of IT spending on 3rd Platform technologies", {}),
        ("Edge computing in cloud deployments", "share of organizations' cloud deployments including edge computing", {"value": "over 40", "note": "Also: 25% of endpoint devices and systems execute AI algorithms."}),
        ("Microservices architectures", "share of new apps with microservices architectures", {"note": "Also: 35% of production apps cloud native."}),
        ("Low-code developers", "growth in developer population from developers producing code without custom scripting", {}),
        ("New logical apps", "number of new logical apps created 2018-2023", {"value": "500 million", "unit": "apps", "target_year": 2023}),
        ("Non-x86 cloud compute", "share of public cloud computing on non-x86 processors", {"note": "Also: vertical SaaS spend exceeds horizontal apps by 2022."}),
        ("AI-enabled interfaces", "share of screen-based apps replaced by AI-enabled UIs and process automation", {"value": "33", "unit": "% (one-third)", "note": "Also: by 2022, 30% of enterprises use conversational speech tech for customer engagement."}),
        ("Encryption, AI security, blockchain identity", "share of servers encrypting data at rest and in motion", {"note": "Also: over 50% of security alerts handled by AI automation; 150 million people with blockchain-based digital identities."}),
        ("Cloud megaplatform concentration", "share of IaaS/PaaS deployments hosted by top 4 cloud megaplatforms", {"note": "Also: by 2024, 90% of G1000 mitigate lock-in through multicloud/hybrid tools."}),
    ],
    "US43171317": [  # IT Industry 2018
        ("Digitized global GDP", "share of global GDP digitized", {"value": "at least 50"}),
        ("Digital transformation platform strategy", "share of enterprises with a fully articulated DX platform strategy", {}),
        ("Cloud spending", "enterprise spending on cloud services and cloud-enabling hardware, software and services", {"value": "over 530", "unit": "USD billion", "note": "Also: cloud environment 20% at the edge, over 15% non-x86, over 90% multicloud."}),
        ("AI in enterprise apps", "share of digital transformation initiatives using AI services", {"target_year": 2019, "note": "Also: by 2021, 75% of commercial enterprise apps use AI, over 90% of consumers interact with support bots, over 50% of new industrial robots leverage AI."}),
        ("Microservices and serverless", "share of application development on cloud platforms using microservices and cloud functions", {"note": "Also: over 95% of new microservices deployed in containers."}),
        ("AR, voice and biometric interfaces", "share of field service techs using augmented reality", {"note": "Also: over 25% of info workers use AR, nearly 50% of new mobile apps use voice, 50% of consumer-facing G2000 use biometric sensors."}),
        ("Blockchain for digital trust", "share of G2000 using blockchain services", {"value": "at least 25", "note": "Also: by 2020, 25% of top transaction banks, nearly 30% of manufacturers and retailers, 20% of healthcare organizations use blockchain in production."}),
        ("Data as a service revenue", "share of large enterprises generating revenue from data as a service", {}),
        ("Low-code developers", "share of business applications built by nontraditional developers", {"value": "20", "target_year": 2021, "note": "Also: 30% of new application features; 60% by 2027."}),
        ("Open API ecosystems", "share of G2000 with one-third of digital services interactions through open API ecosystems", {"value": "more than 50", "unit": "% (more than half)"}),
    ],
    "259850": [  # IT Industry 2016
        ("Digital transformation in corporate strategy", "share of G2000 CEOs with DX at the center of corporate strategy", {"value": "67", "unit": "% (two-thirds)"}),
        ("3rd Platform share of IT spending", "share of organizations' IT spending on 3rd Platform technologies", {"value": "over 50", "note": "Also: over 60% by 2020."}),
        ("Cloud share of IT spending", "share of IT spending that is cloud based", {"value": "at least 50", "note": "Also: by 2020, 60% of IT infrastructure and 60-70% of software, services and technology spending."}),
        ("Software development capacity", "change in software development capabilities of enterprises with DX strategies", {"value": "more than 2", "unit": "x", "note": "Also: two-thirds of their coders on strategic DX apps."}),
        ("Enterprise data pipelines", "expansion of external data sources by enterprises with DX strategies", {"value": "3 to 5", "unit": "x", "note": "Also: delivery of data to market up 100-fold or more."}),
        ("IoT devices", "installed IoT devices", {"value": "22 billion", "unit": "devices", "note": "Also: over 200,000 new IoT apps and services."}),
        ("Cognitive services in apps", "share of developer teams embedding cognitive services", {"value": "over 50", "note": "Also: U.S. enterprises save $60+ billion a year by 2020."}),
        ("Industry cloud platforms", "share of enterprises creating or partnering with industry cloud platforms", {"value": "over 50"}),
        ("Digital front door", "share of B2C enterprises overhauling their digital front door", {"value": "80", "note": "Also: 60% of B2B enterprises; support for 1,000-10,000 times more customers and touch points."}),
        ("IT vendor landscape", "share of IT vendors that will not exist as known today", {"value": "more than 30"}),
    ],
    # ---------------- CIO Agenda ----------------
    "US52641324": [  # CIO Agenda 2025
        ("Regulatory divergence", "share of G1000 struggling with divergent regulatory changes", {}),
        ("AI governance policies", "share of organizations formalizing AI risk policies and oversight", {}),
        ("Technical debt remediation", "share of CIOs driving technical debt remediation initiatives", {}),
        ("AI stuck in experimentation", "share of organizations stuck in experimental point-solution AI phase", {"value": "over 33", "unit": "% (over one-third)"}),
        ("Responsible AI road maps", "share of CIOs leading a responsible AI road map", {}),
        ("Security strategy diversification", "share of CIOs diversifying security strategies", {}),
        ("Sustainability in technology projects", "share of CIOs accountable for embedding sustainability goals in technology projects", {}),
        ("AI for incident detection", "share of organizations effectively using AI-infused apps for incident detection and resolution", {"value": "50", "note": "Phrased as 'just 50%'."}),
        ("External CIO hiring", "share of G1000 CIOs hired from outside the organization", {}),
        ("Digital and AI skills tools", "share of G1000 adopting tools to close the digital and AI skills gap", {}),
    ],
    "US51294523": [  # CIO Agenda 2024
        ("Organizational change for AI", "share of CIOs using organizational changes to harness AI, automation and analytics", {}),
        ("GenAI adoption pressure", "share of CIOs facing pressure to adopt GenAI and deep intelligence", {}),
        ("Embedded cybersecurity", "share of CIOs integrating cybersecurity directly into systems and processes", {}),
        ("Strategic data management", "share of CIOs prioritizing strategic data management", {}),
        ("Digital revenue goals", "share of CIOs not meeting 2025 digital revenue goals", {"value": "67", "unit": "% (two-thirds)", "target_year": 2025, "timing": "in"}),
        ("Federated AI governance", "share of CIOs establishing federated AI governance with LOB executives", {"target_year": 2026}),
        ("Early GenAI adoption", "share of CIOs embracing GenAI", {}),
        ("Automated regulatory compliance and ESG", "share of CIOs motivated to automate regulatory compliance and ESG", {"value": "nearly 50", "unit": "% (nearly half)", "target_year": 2025}),
        ("CIO-CMO customer data strategy", "share of CIOs forging unified strategies with CMOs", {}),
        ("GenAI and low-code development", "share of CIOs leveraging in-house developers and GenAI/low-code tools", {}),
    ],
    "US49743322": [  # CIO Agenda 2023
        ("CIO role challenged by LOB", "share of CIOs whose roles are challenged by LOB counterparts", {}),
        ("Pervasive IT governance", "share of CIOs governing pervasive IT", {}),
        ("Operating model design", "share of CIOs using operating model design", {}),
        ("Resilience as competitive advantage", "share of CIOs harnessing resilience capabilities", {}),
        ("Intelligent enterprise", "share of CIOs achieving a true intelligent enterprise", {"value": "45", "note": "Phrased as 'only 45%'."}),
        ("Embedded intelligence and automation", "share of CIOs augmenting critical systems with embedded intelligence", {}),
        ("Edge operational data", "share of CIOs relying more on edge operational data", {}),
        ("Ethical employee insight technology", "share of CIOs tasked with ethical use of technology for employee insight", {}),
        ("Sustainable IT governance", "share of CIOs governing selection of clean IT", {}),
        ("Opex resets in IT spending", "size of lasting opex resets in software and resources", {"value": "10 to 30", "unit": "%", "note": "Condition: 40% or more of IT spending as a service."}),
    ],
    "US48297821": [  # CIO Agenda 2022
        ("Tech-based empowerment cycle", "share of CIOs sustaining tech-based empowerment, agility and resilience", {}),
        ("CIOs measured on business model cocreation", "share of CIOs measured on cocreating business models", {}),
        ("Technical debt management", "share of CIOs and CFOs enacting formal technical debt management", {}),
        ("Hybrid workplace user support", "share of CIOs reimagining user support with COE-based teams", {}),
        ("CIO-led data governance", "share of organizations with inhibiting data practices empowering CIOs to lead data governance investments", {}),
        ("Modern digital infrastructure capability", "share of CIOs failing to evolve IT's capability", {}),
        ("IT spending as direct LOB cost", "share of organizations shifting at least 25% of IT spending to direct LOB cost", {}),
        ("Multifactor authentication", "share of CIOs embracing ecosystemwide MFA", {"target_year": 2022}),
        ("Industry ecosystem innovation", "share of CIOs harnessing industry ecosystem capabilities", {}),
        ("Sustainable IT", "share of G2000 CIOs required to implement sustainable IT", {}),
    ],
    "US46010920": [  # CIO Agenda 2021
        ("Frontline worker empowerment", "share of CIOs empowering frontline workers with data, AI and security", {}),
        ("Trust protection failures", "share of CIOs failing to protect trust", {}),
        ("Pandemic technical debt", "share of CIOs shadowed by pandemic technical debt", {}),
        ("CIOs in business decision making", "share of CIOs integral to business decision making", {}),
        ("Robotization and automation", "share of CIOs accelerating robotization, automation and augmentation", {}),
        ("CIO-led adversity centers", "share of enterprises with CIO-led adversity centers", {}),
        ("Customer behavior intelligence", "share of CIOs implementing intelligent capabilities to sense customer behavior", {}),
        ("Low-code/no-code governance", "share of CIOs implementing governance for low-code/no-code tools", {}),
        ("Control systems for ecosystems", "share of CIOs implementing ecosystem, application and infrastructure control systems", {}),
        ("Employee health and location data", "share of CIOs absorbing accountability for employee health, welfare and location data", {}),
    ],
    "US45578619": [  # CIO Agenda 2020
        ("Self-service digital tool mashup", "share of digitally advanced organizations whose IT strategy becomes a self-service mashup of digital tools", {}),
        ("Entrepreneurial CIOs", "share of CIOs who are entrepreneurial leaders", {}),
        ("Legacy modernization", "share of enterprises aggressively modernizing legacy systems", {"target_year": 2023}),
        ("Container/API playbook", "share of IT organizations implementing a container/abstraction/API playbook", {}),
        ("IT as designer and integrator", "share of IT organizations transitioned to designers and integrators", {}),
        ("Weekly code deployment", "share of IT organizations deploying at least weekly code updates", {}),
        ("CIO co-leading innovation", "share of CIOs co-leading innovation", {}),
        ("AI for IT operations", "share of enterprise IT organizations with AI for IT operations as principal initiative", {}),
        ("Real-time IT resource allocation", "share of CIOs reshaping IT resources for real-time allocation", {}),
        ("Employee experience programs", "share of CIOs implementing formal employee experience programs", {}),
    ],
    "US44390218": [  # CIO Agenda 2019
        ("Agile connectivity via APIs", "share of CIOs delivering agile connectivity via APIs", {}),
        ("AI for IT operations", "share of CIOs applying data and AI to IT operations", {"target_year": 2021}),
        ("AI and data governance", "share of enterprises tasking CIOs to modernize governance for AI, ML, privacy and ethics", {}),
        ("IT-built digital strategies", "share of successful digital strategies built by a transformed IT organization", {}),
        ("Business KPIs in IT compensation", "share of IT executive leadership compensated on business KPIs", {}),
        ("Digital trust framework", "share of CIOs initiating a digital trust framework", {}),
        ("Empowered IT product teams", "share of CIOs who fail by not shifting to empowered IT product teams", {}),
        ("Emerging tech talent gap", "share of global demand for emerging technology talent left unfilled", {"value": "at least 30"}),
        ("Agile/DevOps beyond IT", "share of CIOs expanding agile/DevOps into the wider business", {}),
        ("Edge, OT and IT governance", "share of CIOs who fail professionally by not managing edge/OT/IT divides", {}),
    ],
    "CIO2018": [  # CIO Agenda 2018 (secondary copy; order as published by InfotechLead)
        ("Digital agenda priorities", "share of CIOs with experiential engagement, data monetization or digital business at scale at top of agenda", {}),
        ("Digital objectives shortfall", "share of CIOs and enterprises failing to meet all digital objectives", {}),
        ("CIOs as digital business leaders", "share of CIOs who crossed the digital divide prevailing as digital business leaders", {}),
        ("Re-platforming", "share of CIOs completing infrastructure and application re-platforming", {}),
        ("DX platforms", "share of IT organizations deploying DX platforms", {}),
        ("Authentication and trust in cybersecurity", "share of CIOs refocusing cybersecurity on authentication and trust", {}),
        ("Vision-driven leadership", "share of CIOs using vision- and mission-driven leadership", {}),
        ("Digital governance models", "share of CIOs adopting new digital governance models", {}),
        ("Product model with design thinking and DevOps", "share of CIOs moving to a product model", {}),
        ("IT business model shift to products", "share of CIOs shifting IT from projects to digitally oriented products", {}),
    ],
    "US41845916": [  # CIO Agenda 2017
        ("IT projects monetizing data", "share of IT projects creating digital services and revenue streams that monetize data", {}),
        ("Customer- and ecosystem-facing IT services", "share of IT organizations creating customer- and ecosystem-facing services", {}),
        ("CIO leadership in digital transformation", "share of CIOs kept from DX leadership roles", {"target_year": 2017}),
        ("Leading in 3D", "share of CIOs embracing an innovation-cycle leadership approach", {}),
        ("IT and LOB technology team linkages", "share of CIOs advancing DX through links with LOB technology teams", {"target_year": 2018}),
        ("Bimodal IT technical debt", "share of bimodal IT organizations accumulating crippling technical debt", {}),
        ("Physical to digital focus", "share of CIOs shifting primary focus from physical to digital", {"target_year": 2018}),
        ("Platformization and DevOps", "share of CIOs focusing on platformization with DevOps", {}),
        ("Start-up-like IT culture", "share of IT organizations shifting to a start-up-like culture", {}),
        ("Global risk portfolios", "share of CIOs helping drive global risk portfolios", {}),
    ],
    "252235": [  # CIO Agenda 2015 (decision imperatives)
        ("CIO time on analytics, cybersecurity and digital revenue", "share of CIO time focused on analytics, cybersecurity and new digital revenue streams", {}),
        ("Real-time IT as a service", "share of global competitive strategies requiring real-time 3rd Platform ITaaS", {}),
        ("Security as CEO priority", "share of CEOs of global enterprises with security as a top 3 business priority", {}),
        ("DevOps", "share of CIOs using DevOps as primary tool", {}),
        ("Architectural framework", "share of CIOs delivering a new architectural framework", {}),
        ("Chief Digital Officer", "share of CIOs in global organizations supplanted by the CDO for IT-enabled products and digital services", {}),
        ("Premature obsolescence of IT assets", "share of CIOs accelerating 3rd Platform migration", {}),
        ("Pan-enterprise data strategy", "share of CIOs of global organizations with a pan-enterprise data and analytics strategy", {}),
        ("3rd Platform sourcing failures", "share of 3rd Platform vendor sourcing relationships that fail", {}),
        ("Open standards ecosystem", "share of CIOs relinquishing traditional technology control for an open standards framework", {}),
    ],
    "CIO2016": [  # CIO Agenda 2016 (secondary, partial; order is the article's, not IDC's)
        ("IT resources for digital revenue", "share of IT resources spent to support new digital revenue streams", {}),
        ("Data transformation and governance", "share of global CIOs initiating a data transformation and governance framework", {}),
        ("Contain-and-control security", "share of IT organizations shifting to contain-and-control security", {}),
        ("Digital transformation scaling failures", "share of DX initiatives unable to scale for lack of strategic architecture", {}),
    ],
}
